// import 'package:base_starter/src/core/utils/extensions/colors_extension.dart';

// final _lightAppColors = AppColorsExtension(
//   primary: DarkTheme.colorScheme.primary,
//   onPrimary: DarkTheme.colorScheme.onPrimary,
//   secondary: DarkTheme.colorScheme.secondary,
//   onSecondary: DarkTheme.colorScheme.onSecondary,
//   error: DarkTheme.colorScheme.error,
//   onError: DarkTheme.colorScheme.onError,
//   background: DarkTheme.colorScheme.background,
//   onBackground: DarkTheme.colorScheme.onBackground,
//   surface: DarkTheme.colorScheme.surface,
//   onSurface: DarkTheme.colorScheme.onSurface,
//   standart: Colors.white,
//   divider: AppPalette.gray200,
//   text: AppPalette.abyss,
//   primaryIcon: AppPalette.primaryColor,
//   selectedTile: AppPalette.accent100,
//   grayOpacity: Colors.white,
//   grayOpacityText: const Color.fromARGB(255, 83, 83, 83),
//   blueOrigin: const Color(0xFF2248CD),
//   orange500: const Color(0xFFF97316),
//   green500: const Color(0xFF22C55E),
//   scaffoldBackground: AppPalette.background,
//   border: AppPalette.gray300,
//   card: Colors.white,
//   shadow: AppPalette.gray200,
//   shimmerBase: const Color(0xffB4B4B4),
//   shimmerHighlight: AppPalette.white,
// );
